kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-cephfs-provisioner-rb
subjects:
  - kind: ServiceAccount
    name: csi-cephfs-provisioner-sa
    namespace: system
roleRef:
  kind: Role
  name: csi-cephfs-provisioner-role
  apiGroup: rbac.authorization.k8s.io
