kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-cephfs-provisioner-role
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
