apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ocs-status-reporter
rules:
  - apiGroups:
      - ocs.openshift.io
    resources:
      - storageclients
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - update
