kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ocs-status-reporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ocs-client-operator-status-reporter
subjects:
  - kind: ServiceAccount
    name: ocs-client-operator-status-reporter
