kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: status-reporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: status-reporter
subjects:
  - kind: ServiceAccount
    name: status-reporter
    namespace: system
