# permissions for end users to view storageclassclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: storageclassclaim-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ocs-client-operator
    app.kubernetes.io/part-of: ocs-client-operator
    app.kubernetes.io/managed-by: kustomize
  name: storageclassclaim-viewer-role
rules:
- apiGroups:
  - ocs.openshift.io
  resources:
  - storageclassclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ocs.openshift.io
  resources:
  - storageclassclaims/status
  verbs:
  - get
